export enum ProblemTypes {
  INCONVENIENT_ROUTE = 'INCONVENIENT_ROUTE',
  LONG_WAITING = 'LONG_WAITING',
  BUS_STOP_QUEUE = 'BUS_STOP_QUEUE',
  CROWDED_BUS = 'CROWDED_BUS',
  TRAFFIC_JAM = 'TRAFFIC_JAM',
  OTHER = 'OTHER',
}